name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'  # Trigger on push to tags that start with 'v', e.g., 'v1.0', 'v2.0.1'

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner to execute the steps

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for both client and server
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'  # Change this to the version you're using

      # Step 3: Install frontend dependencies (React app)
      - name: Install frontend dependencies
        working-directory: ./client   # This points to the client directory
        run: |
          npm install

      # Step 4: Install backend dependencies (Node.js app)
      - name: Install backend dependencies
        working-directory: ./server   # This points to the server directory
        run: |
          npm install

      # Step 5: Build frontend (React app)
      - name: Build frontend
        working-directory: ./client
        run: |
          npm run build  # Create a production build (in the dist folder)

      # Step 6: Build Docker images for both frontend and backend

      # Build the frontend Docker image
      - name: Build frontend Docker image
        run: |
          docker build -t auth-frontend:${{ github.ref }} ./client  # Tag image with Git tag (e.g., 'v1.0')

      # Build the backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -t auth-backend:${{ github.ref }} ./server  # Tag image with Git tag (e.g., 'v1.0')

      # Step 7: Log in to Docker Hub and push both images

      # Docker login (using a more secure way with --password-stdin)
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Push frontend Docker image
      - name: Push frontend Docker image
        run: |
          docker push auth-frontend:${{ github.ref }}  # Push the frontend image to Docker Hub

      # Push backend Docker image
      - name: Push backend Docker image
        run: |
          docker push auth-backend:${{ github.ref }}  # Push the backend image to Docker Hub

      # Step 8: Save images as artifacts (optional, if you want to download them later)
      - name: Save Docker images as artifacts
        run: |
          docker save -o auth-frontend-${{ github.ref }}.tar auth-frontend:${{ github.ref }}
          docker save -o auth-backend-${{ github.ref }}.tar auth-backend:${{ github.ref }}
          
      # Step 9: Upload Docker images as artifacts (updated to v3)
      - name: Upload Docker images as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: |
            auth-frontend-${{ github.ref }}.tar
            auth-backend-${{ github.ref }}.tar
